CREATE TYPE "OrganizationType" AS ENUM ('CLIENT', 'CREATOR');
CREATE TYPE "OrganizationRole" AS ENUM ('OWNER', 'ADMIN', 'PROJECT_MANAGER', 'REVIEWER', 'FINANCE', 'MEMBER');
CREATE TYPE "VerificationStatus" AS ENUM ('UNVERIFIED', 'PENDING', 'VERIFIED', 'REJECTED');
CREATE TYPE "PaymentStatus" AS ENUM ('PENDING', 'FUNDED', 'RELEASED', 'PARTIALLY_REFUNDED', 'REFUNDED', 'FAILED');
CREATE TYPE "LedgerEntryType" AS ENUM ('FUND', 'HOLD', 'RELEASE', 'PLATFORM_FEE', 'REFUND', 'SETTLEMENT');
CREATE TYPE "CommentStatus" AS ENUM ('OPEN', 'RESOLVED');

ALTER TABLE "Application" ADD COLUMN "promisedDays" INTEGER, ADD COLUMN "quoteAmount" DECIMAL(12,2);
ALTER TABLE "CreatorProfile" ADD COLUMN "verificationStatus" "VerificationStatus" NOT NULL DEFAULT 'UNVERIFIED';
ALTER TABLE "Order" ADD COLUMN "budgetAmount" DECIMAL(12,2), ADD COLUMN "clientOrganizationId" TEXT, ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'CNY', ADD COLUMN "maxRevisions" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "SubOrder" ADD COLUMN "creatorNetAmount" DECIMAL(12,2), ADD COLUMN "feeRate" DECIMAL(5,4), ADD COLUMN "grossAmount" DECIMAL(12,2), ADD COLUMN "platformFee" DECIMAL(12,2);

CREATE TABLE "UserRoleAssignment" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "role" "UserRole" NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "UserRoleAssignment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Organization" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "type" "OrganizationType" NOT NULL, "description" TEXT NOT NULL DEFAULT '', "creatorId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Organization_pkey" PRIMARY KEY ("id"));
CREATE TABLE "OrganizationMember" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "userId" TEXT NOT NULL, "role" "OrganizationRole" NOT NULL DEFAULT 'MEMBER', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "OrganizationMember_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CreatorServicePackage" ("id" TEXT NOT NULL, "profileId" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "deliveryDays" INTEGER NOT NULL, "revisions" INTEGER NOT NULL DEFAULT 1, "price" DECIMAL(12,2) NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "CreatorServicePackage_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Availability" ("id" TEXT NOT NULL, "profileId" TEXT NOT NULL, "startsAt" TIMESTAMP(3) NOT NULL, "endsAt" TIMESTAMP(3) NOT NULL, "note" TEXT NOT NULL DEFAULT '', CONSTRAINT "Availability_pkey" PRIMARY KEY ("id"));
CREATE TABLE "OrderCollaborator" ("id" TEXT NOT NULL, "orderId" TEXT NOT NULL, "userId" TEXT NOT NULL, "role" "OrganizationRole" NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "OrderCollaborator_pkey" PRIMARY KEY ("id"));
CREATE TABLE "MediaAsset" ("id" TEXT NOT NULL, "deliveryId" TEXT, "uploaderId" TEXT NOT NULL, "name" TEXT NOT NULL, "url" TEXT NOT NULL, "mimeType" TEXT NOT NULL, "size" BIGINT, "checksum" TEXT, "aigc" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "MediaAsset_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TimecodeComment" ("id" TEXT NOT NULL, "deliveryId" TEXT NOT NULL, "authorId" TEXT NOT NULL, "timecodeMs" INTEGER NOT NULL, "body" TEXT NOT NULL, "status" "CommentStatus" NOT NULL DEFAULT 'OPEN', "resolvedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TimecodeComment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PaymentIntent" ("id" TEXT NOT NULL, "subOrderId" TEXT NOT NULL, "provider" TEXT NOT NULL DEFAULT 'SANDBOX', "providerRef" TEXT, "status" "PaymentStatus" NOT NULL DEFAULT 'PENDING', "grossAmount" DECIMAL(12,2) NOT NULL, "platformFee" DECIMAL(12,2) NOT NULL, "creatorNetAmount" DECIMAL(12,2) NOT NULL, "currency" TEXT NOT NULL DEFAULT 'CNY', "fundedAt" TIMESTAMP(3), "releasedAt" TIMESTAMP(3), "refundedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "PaymentIntent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "LedgerEntry" ("id" TEXT NOT NULL, "paymentIntentId" TEXT NOT NULL, "type" "LedgerEntryType" NOT NULL, "amount" DECIMAL(12,2) NOT NULL, "currency" TEXT NOT NULL DEFAULT 'CNY', "note" TEXT NOT NULL DEFAULT '', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "LedgerEntry_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Settlement" ("id" TEXT NOT NULL, "paymentIntentId" TEXT NOT NULL, "amount" DECIMAL(12,2) NOT NULL, "status" "PaymentStatus" NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Settlement_pkey" PRIMARY KEY ("id"));
CREATE TABLE "FeeRule" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "rate" DECIMAL(5,4) NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "effectiveAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FeeRule_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Conversation" ("id" TEXT NOT NULL, "orderId" TEXT, "subOrderId" TEXT, "title" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Conversation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Message" ("id" TEXT NOT NULL, "conversationId" TEXT NOT NULL, "authorId" TEXT NOT NULL, "body" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Message_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Notification" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "title" TEXT NOT NULL, "body" TEXT NOT NULL, "href" TEXT, "readAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Notification_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AdminDelegation" ("id" TEXT NOT NULL, "orderId" TEXT NOT NULL, "granterId" TEXT NOT NULL, "adminId" TEXT NOT NULL, "actions" TEXT[], "reason" TEXT NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "usedAt" TIMESTAMP(3), "revokedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AdminDelegation_pkey" PRIMARY KEY ("id"));

INSERT INTO "UserRoleAssignment" ("id","userId","role") SELECT 'role_' || "id", "id", "role" FROM "User" ON CONFLICT DO NOTHING;
INSERT INTO "Organization" ("id","name","type","creatorId","updatedAt") SELECT 'org_' || "id", "name" || '的工作空间', CASE WHEN "role"='CREATOR' THEN 'CREATOR'::"OrganizationType" ELSE 'CLIENT'::"OrganizationType" END, "id", CURRENT_TIMESTAMP FROM "User" WHERE "role" <> 'ADMIN';
INSERT INTO "OrganizationMember" ("id","organizationId","userId","role","updatedAt") SELECT 'orgmember_' || "id", 'org_' || "id", "id", 'OWNER', CURRENT_TIMESTAMP FROM "User" WHERE "role" <> 'ADMIN';
UPDATE "Order" SET "clientOrganizationId"='org_' || "clientId" WHERE "clientOrganizationId" IS NULL;
INSERT INTO "FeeRule" ("id","name","rate") VALUES ('fee_default','平台标准服务费',0.02);

CREATE UNIQUE INDEX "UserRoleAssignment_userId_role_key" ON "UserRoleAssignment"("userId", "role");
CREATE INDEX "UserRoleAssignment_role_idx" ON "UserRoleAssignment"("role");
CREATE INDEX "Organization_type_createdAt_idx" ON "Organization"("type", "createdAt");
CREATE UNIQUE INDEX "OrganizationMember_organizationId_userId_key" ON "OrganizationMember"("organizationId", "userId");
CREATE INDEX "OrganizationMember_userId_role_idx" ON "OrganizationMember"("userId", "role");
CREATE INDEX "Availability_profileId_startsAt_endsAt_idx" ON "Availability"("profileId", "startsAt", "endsAt");
CREATE UNIQUE INDEX "OrderCollaborator_orderId_userId_role_key" ON "OrderCollaborator"("orderId", "userId", "role");
CREATE INDEX "OrderCollaborator_userId_idx" ON "OrderCollaborator"("userId");
CREATE INDEX "MediaAsset_deliveryId_createdAt_idx" ON "MediaAsset"("deliveryId", "createdAt");
CREATE INDEX "TimecodeComment_deliveryId_timecodeMs_idx" ON "TimecodeComment"("deliveryId", "timecodeMs");
CREATE UNIQUE INDEX "PaymentIntent_subOrderId_key" ON "PaymentIntent"("subOrderId");
CREATE UNIQUE INDEX "PaymentIntent_providerRef_key" ON "PaymentIntent"("providerRef");
CREATE INDEX "LedgerEntry_paymentIntentId_createdAt_idx" ON "LedgerEntry"("paymentIntentId", "createdAt");
CREATE INDEX "Message_conversationId_createdAt_idx" ON "Message"("conversationId", "createdAt");
CREATE INDEX "Notification_userId_readAt_createdAt_idx" ON "Notification"("userId", "readAt", "createdAt");
CREATE INDEX "AdminDelegation_adminId_expiresAt_idx" ON "AdminDelegation"("adminId", "expiresAt");

ALTER TABLE "UserRoleAssignment" ADD CONSTRAINT "UserRoleAssignment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Organization" ADD CONSTRAINT "Organization_creatorId_fkey" FOREIGN KEY ("creatorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "OrganizationMember" ADD CONSTRAINT "OrganizationMember_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OrganizationMember" ADD CONSTRAINT "OrganizationMember_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CreatorServicePackage" ADD CONSTRAINT "CreatorServicePackage_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "CreatorProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Availability" ADD CONSTRAINT "Availability_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "CreatorProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Order" ADD CONSTRAINT "Order_clientOrganizationId_fkey" FOREIGN KEY ("clientOrganizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "OrderCollaborator" ADD CONSTRAINT "OrderCollaborator_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MediaAsset" ADD CONSTRAINT "MediaAsset_deliveryId_fkey" FOREIGN KEY ("deliveryId") REFERENCES "DeliveryVersion"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MediaAsset" ADD CONSTRAINT "MediaAsset_uploaderId_fkey" FOREIGN KEY ("uploaderId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TimecodeComment" ADD CONSTRAINT "TimecodeComment_deliveryId_fkey" FOREIGN KEY ("deliveryId") REFERENCES "DeliveryVersion"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TimecodeComment" ADD CONSTRAINT "TimecodeComment_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PaymentIntent" ADD CONSTRAINT "PaymentIntent_subOrderId_fkey" FOREIGN KEY ("subOrderId") REFERENCES "SubOrder"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "LedgerEntry" ADD CONSTRAINT "LedgerEntry_paymentIntentId_fkey" FOREIGN KEY ("paymentIntentId") REFERENCES "PaymentIntent"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Settlement" ADD CONSTRAINT "Settlement_paymentIntentId_fkey" FOREIGN KEY ("paymentIntentId") REFERENCES "PaymentIntent"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Conversation" ADD CONSTRAINT "Conversation_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Conversation" ADD CONSTRAINT "Conversation_subOrderId_fkey" FOREIGN KEY ("subOrderId") REFERENCES "SubOrder"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Message" ADD CONSTRAINT "Message_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "Conversation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Message" ADD CONSTRAINT "Message_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AdminDelegation" ADD CONSTRAINT "AdminDelegation_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AdminDelegation" ADD CONSTRAINT "AdminDelegation_granterId_fkey" FOREIGN KEY ("granterId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AdminDelegation" ADD CONSTRAINT "AdminDelegation_adminId_fkey" FOREIGN KEY ("adminId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
