"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { api } from "@/lib/client";

export function OrderAction({id,action,label,danger=false}:{id:string;action:string;label:string;danger?:boolean}){const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState("");return <div>{error&&<div className="notice error" style={{marginBottom:8}}>{error}</div>}<button className={`button ${danger?"danger":""}`} disabled={busy} onClick={async()=>{setBusy(true);try{await api(`/api/orders/${id}`,{method:"PATCH",body:JSON.stringify({action})});router.refresh()}catch(e){setError(e instanceof Error?e.message:"操作失败")}finally{setBusy(false)}}}>{busy?"处理中…":label}</button></div>}

export function ApplyForm({orderId}:{orderId:string}){const router=useRouter();const[open,setOpen]=useState(false);const[error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api(`/api/orders/${orderId}/applications`,{method:"POST",body:JSON.stringify({pitch:f.get("pitch"),portfolioIds:[]})});setOpen(false);router.refresh()}catch(e){setError(e instanceof Error?e.message:"报名失败")}}return open?<form className="card form" onSubmit={submit} style={{marginTop:16}}>{error&&<div className="notice error">{error}</div>}<div className="field"><label>报名说明</label><textarea className="input" name="pitch" required placeholder="说明你的相关经验、制作思路和可投入时间"/></div><div className="row"><button className="button">确认报名</button><button type="button" className="button secondary" onClick={()=>setOpen(false)}>取消</button></div></form>:<button className="button" onClick={()=>setOpen(true)}>报名这个订单</button>}

export function ApplicantSelector({orderId,applications,max}:{orderId:string;applications:{id:string;name:string}[];max:number}){const router=useRouter();const[selected,setSelected]=useState<string[]>([]);const[error,setError]=useState("");return <div>{error&&<div className="notice error" style={{marginBottom:10}}>{error}</div>}<div className="grid">{applications.map(a=><label className="row card" key={a.id} style={{padding:14}}><input type="checkbox" checked={selected.includes(a.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,a.id]:v.filter(x=>x!==a.id))}/><strong>{a.name}</strong></label>)}</div><button className="button" style={{marginTop:14}} disabled={!selected.length||selected.length>max} onClick={async()=>{try{await api(`/api/orders/${orderId}/select`,{method:"POST",body:JSON.stringify({applicationIds:selected})});router.refresh()}catch(e){setError(e instanceof Error?e.message:"中选失败")}}}>确认中选 {selected.length} 人</button></div>}
