"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { api } from "@/lib/client";

type Item={id:string;code:string;status:string;creatorId:string;creatorConfirmedAt?:string|null;objection?:string|null;objectionResolvedAt?:string|null;grossAmount?:string|null;platformFee?:string|null;creatorNetAmount?:string|null;payment?:{status:string}|null;access:{manage:boolean;review:boolean;finance:boolean};order:{id:string;title:string;clientId:string;deadline:string};creator:{name:string};briefSnapshot:{content:Record<string,unknown>};deliveries:{id:string;version:number;title:string;fileUrl:string;createdAt:string;compliance:unknown;revisions:unknown[];comments:{id:string;timecodeMs:number;body:string;status:string;author:{name:string}}[]}[];rightsReceipt?:{scope:string}|null;reviews:{authorId:string}[]};
const status:Record<string,string>={PENDING_CONFIRMATION:"待确认 Brief",IN_PRODUCTION:"制作中",SUBMITTED:"已提交",NEEDS_CHANGES:"需修改",PENDING_ACCEPTANCE:"待验收",ACCEPTED:"已验收",CANCELLED:"已取消"};
export function WorkflowCard({item,user}:{item:Item;user:{id:string;role:string}}){const router=useRouter();const[mode,setMode]=useState("");const[error,setError]=useState("");const latest=item.deliveries[0];async function post(path:string,payload:unknown){setError("");try{await api(path,{method:"POST",body:JSON.stringify(payload)});setMode("");router.refresh()}catch(e){setError(e instanceof Error?e.message:"操作失败")}}
async function submitDelivery(form:FormData){let fileUrl=String(form.get("fileUrl")||"");const file=form.get("file");if(file instanceof File&&file.size){const upload=new FormData();upload.set("file",file);const result=await api<{url:string}>("/api/uploads",{method:"POST",body:upload});fileUrl=result.url}if(!fileUrl)throw new Error("请上传交付文件或填写文件地址");await post(`/api/suborders/${item.id}/deliveries`,{title:form.get("title"),fileUrl,previewUrl:form.get("previewUrl"),note:form.get("note"),aiTools:String(form.get("aiTools")||"").split(/[,，]/).filter(Boolean),materialSources:form.get("materialSources"),commercialLicense:form.has("commercialLicense"),portraitAuthorization:form.has("portraitAuthorization"),voiceAuthorization:form.has("voiceAuthorization"),brandAuthorization:form.has("brandAuthorization")})}
function form(handler:(f:FormData)=>Promise<void>,children:React.ReactNode){return <form className="form" onSubmit={async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();await handler(new FormData(e.currentTarget))}}>{children}</form>}
return <article className="card"><div className="row between wrap"><div><div className="eyebrow">{item.code}</div><h2 style={{marginTop:6}}>{item.order.title}</h2><p className="muted" style={{margin:"5px 0"}}>创作者：{item.creator.name} · 截止 {new Date(item.order.deadline).toLocaleDateString("zh-CN")}</p></div><span className={`chip ${item.status==="ACCEPTED"?"green":"blue"}`}>{status[item.status]||item.status}</span></div>{error&&<div className="notice error" style={{marginTop:12}}>{error}</div>}<div className="divider"/>
{item.status==="PENDING_CONFIRMATION"&&user.id===item.creatorId&&!item.creatorConfirmedAt&&<div><p>中选后必须明确确认冻结的 Brief，发布者完成沙箱托管后才能开始制作。</p><div className="row"><button className="button" onClick={()=>post(`/api/suborders/${item.id}/confirm`,{confirmed:true})}>确认 Brief</button><button className="button secondary" onClick={()=>setMode("object")}>提出异议</button></div>{mode==="object"&&form(async f=>post(`/api/suborders/${item.id}/confirm`,{confirmed:false,objection:f.get("objection")}),<><textarea className="input" name="objection" required placeholder="指出需要重新确认的要求"/><button className="button">提交协商</button></>)}</div>}
{item.status==="PENDING_CONFIRMATION"&&user.id===item.creatorId&&item.creatorConfirmedAt&&<div className="notice">Brief 已确认，等待发布者完成沙箱托管。预计结算 ¥{Number(item.creatorNetAmount||0).toFixed(2)}，平台服务费 ¥{Number(item.platformFee||0).toFixed(2)}。</div>}
{item.status==="PENDING_CONFIRMATION"&&item.access.finance&&item.creatorConfirmedAt&&<div><div className="notice">创作者已确认 Brief。托管金额 ¥{Number(item.grossAmount||0).toFixed(2)}；当前为沙箱资金，不代表真实扣款。</div><button className="button" style={{marginTop:12}} onClick={()=>post(`/api/suborders/${item.id}/payment`,{})}>沙箱托管并开始制作</button></div>}
{item.status==="PENDING_CONFIRMATION"&&item.access.manage&&item.objection&&!item.objectionResolvedAt&&<div><div className="notice error">创作者异议：{item.objection}</div>{form(async f=>{await api(`/api/suborders/${item.id}/confirm`,{method:"PATCH",body:JSON.stringify({resolution:f.get("resolution")})});router.refresh()},<><textarea className="input" name="resolution" required placeholder="填写双方确认后的 Brief 调整结论"/><button className="button">确认已协商，交回创作者确认</button></>)}</div>}
{["IN_PRODUCTION","NEEDS_CHANGES"].includes(item.status)&&user.id===item.creatorId&&<div><button className="button" onClick={()=>setMode("delivery")}>{item.status==="NEEDS_CHANGES"?"提交修改版本":"提交交付版本"}</button>{mode==="delivery"&&form(submitDelivery,<><input className="input" name="title" required placeholder="版本名称"/><div className="field"><label>上传交付文件（最大 100MB）</label><input className="input" name="file" type="file"/></div><div className="field"><label>或填写已有文件地址</label><input className="input" name="fileUrl" type="url" placeholder="https://..."/></div><input className="input" name="previewUrl" type="url" placeholder="预览地址（可选）"/><textarea className="input" name="note" placeholder="本版说明"/><input className="input" name="aiTools" required placeholder="使用的 AI 工具，以逗号分隔"/><textarea className="input" name="materialSources" required placeholder="素材来源和许可说明"/><div className="grid grid-2"><label><input type="checkbox" name="commercialLicense"/> 素材可商用</label><label><input type="checkbox" name="portraitAuthorization"/> 人物肖像已授权</label><label><input type="checkbox" name="voiceAuthorization"/> 克隆声音已授权/未使用</label><label><input type="checkbox" name="brandAuthorization"/> 品牌元素已授权/未使用</label></div><button className="button">提交版本与合规声明</button></>)}</div>}
{item.status==="PENDING_ACCEPTANCE"&&item.access.review&&latest&&<div><div className="row wrap"><span className="chip orange">AIGC 生成内容</span><p>待验收版本：<a href={latest.fileUrl} target="_blank" rel="noreferrer" style={{color:"var(--blue)",fontWeight:700}}>v{latest.version} {latest.title}</a></p></div><div className="row"><button className="button" onClick={()=>setMode("accept")}>验收通过并确权</button>{latest.revisions.length===0&&<button className="button secondary" onClick={()=>setMode("revision")}>退回修改</button>}</div>{mode==="revision"&&form(async f=>post(`/api/suborders/${item.id}/revision`,{criteria:f.get("criteria"),evidence:f.get("evidence"),note:f.get("note")}),<><input className="input" name="criteria" required placeholder="不符合的验收条款"/><input className="input" name="evidence" required placeholder="验证证据或时间点"/><textarea className="input" name="note" required placeholder="具体修改说明"/><button className="button">确认退回</button></>)}{mode==="accept"&&form(async f=>post(`/api/suborders/${item.id}/accept`,{scope:f.get("scope"),verification:f.get("verification"),portfolioPermission:f.has("portfolioPermission")}),<><textarea className="input" name="verification" required placeholder="验收验证说明"/><textarea className="input" name="scope" required defaultValue="最终验收文件的中国境内全渠道商业使用权"/><label><input type="checkbox" name="portfolioPermission"/> 允许创作者公开展示本案例</label><button className="button">确认验收与权利转移</button></>)}</div>}
{latest&&<section className="review-panel"><div className="row between wrap"><strong>v{latest.version} 时间码审阅</strong><span className="chip">{latest.comments.filter(c=>c.status==="OPEN").length} 条待处理</span></div>{latest.comments.length?<div className="comment-list">{latest.comments.map(comment=><div className="comment-row" key={comment.id}><span className="timecode">{Math.floor(comment.timecodeMs/60000)}:{String(Math.floor(comment.timecodeMs/1000)%60).padStart(2,"0")}</span><span><strong>{comment.author.name}</strong><small>{comment.body}</small></span><span className={`chip ${comment.status==="RESOLVED"?"green":"orange"}`}>{comment.status==="RESOLVED"?"已解决":"待处理"}</span>{user.id===item.creatorId&&comment.status==="OPEN"&&<button className="button compact" onClick={async()=>{await api(`/api/deliveries/${latest.id}/comments`,{method:"PATCH",body:JSON.stringify({commentId:comment.id,resolved:true})});router.refresh()}}>标记解决</button>}</div>)}</div>:<p className="muted">当前版本还没有时间码批注。</p>}{user.id===item.order.clientId&&form(async f=>post(`/api/deliveries/${latest.id}/comments`,{timecodeSeconds:Number(f.get("timecodeSeconds")),body:f.get("body")}),<div className="review-form"><input className="input" name="timecodeSeconds" type="number" min="0" step="1" required placeholder="秒数"/><input className="input" name="body" required placeholder="输入该时间点的修改意见"/><button className="button">添加批注</button></div>)}</section>}
{item.status==="ACCEPTED"&&<div><p className="muted">权利确认：{item.rightsReceipt?.scope}</p>{!item.reviews.some(r=>r.authorId===user.id)&&form(async f=>post(`/api/suborders/${item.id}/reviews`,{rating:Number(f.get("rating")),comment:f.get("comment")}),<><div className="row"><select className="input" name="rating" style={{maxWidth:130}}><option value="5">5 分</option><option value="4">4 分</option><option value="3">3 分</option><option value="2">2 分</option><option value="1">1 分</option></select><input className="input" name="comment" required placeholder="基于真实履约写下评价"/><button className="button">提交评价</button></div></>)}</div>}
<div style={{marginTop:16}}><Link href={`/orders/${item.order.id}`} className="muted" style={{fontSize:13}}>查看原订单与验收标准 →</Link></div></article>}
